# Site settings
title: "Yo! Symfony Blog"
name: "Yo! Symfony"

top_menu:
  - { name: Web, url: "https://yosymfony.com" }

comments:
  enabled: false
  disqus_shortname: ""

social_networks:
    twitter: "yosymfony" # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: "https://github.com/yosymfony"
    dribbble: # Your id
    linkedin: # Your URL
    email: # Your email adress you@yoourDomain.com
